In [1]:
"""
날짜 : 2020/08/10
이름 : 권기민
내용 : Numpy(파이썬 수치해석 패키지) 실습하기
"""

'\n    날짜 : 2020/08/10\n    이름 : 권기민\n    내용 : Numpy(파이썬 수치해석 패키지) 실습하기\n'

In [3]:
import numpy as np

In [6]:
# 벡터생성
v1 = np.array([1, 2, 3, 4, 5])
v1

array([1, 2, 3, 4, 5])

In [8]:
v2 = np.arange(5)
v2

array([0, 1, 2, 3, 4])

In [10]:
# 0 ~ 1 사이 임의의 실수 100개
rand1 = np.random.rand(100)
rand1

array([0.55033398, 0.19139831, 0.07888338, 0.64172958, 0.55290563,
       0.66117557, 0.91899999, 0.52176845, 0.29463163, 0.33156788,
       0.49264886, 0.69042079, 0.4582908 , 0.91655407, 0.80060562,
       0.45523872, 0.98065905, 0.80466291, 0.62261908, 0.30638895,
       0.34406975, 0.28166304, 0.61152295, 0.5774351 , 0.60321487,
       0.43086548, 0.71576939, 0.10106729, 0.87160264, 0.79186818,
       0.83576181, 0.78247543, 0.78535431, 0.66198648, 0.91797694,
       0.05176314, 0.58642918, 0.35779213, 0.85985056, 0.08287289,
       0.83188344, 0.68703332, 0.27396687, 0.55512245, 0.92984453,
       0.34179999, 0.11084046, 0.13631108, 0.0175081 , 0.01326569,
       0.87278665, 0.85451505, 0.37391438, 0.39094404, 0.21561039,
       0.20818696, 0.98574247, 0.45339145, 0.13077022, 0.68352254,
       0.79838588, 0.16394006, 0.83228855, 0.28710573, 0.22441094,
       0.99230159, 0.70069074, 0.84451514, 0.12016378, 0.05893442,
       0.383392  , 0.74110049, 0.69974709, 0.44299306, 0.91105

In [13]:
# 표준 정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)
rand2

array([-0.71417813, -0.38704217, -1.89064328, -1.05971205,  1.08780682,
       -1.94082584,  0.50374775, -1.22478932, -0.03487142,  1.5991885 ,
        0.88816663,  0.41864024, -0.65080039,  0.2767399 ,  0.29973903,
       -0.29408794,  0.92218785, -0.74809302,  0.90837202,  1.14572157,
        1.01155601,  2.64499048, -0.19713436,  0.05256846, -0.35969385,
        0.14545768,  0.85480236,  0.1247271 , -0.52368173,  0.11472621,
       -0.87049221,  0.44598201, -1.01331209, -1.76101612, -0.58652465,
       -0.51726301,  1.61005947,  1.24468475, -1.2577919 ,  0.40014103,
        0.74357908,  2.09640581, -1.4744207 ,  1.58906021, -0.45705384,
       -0.34960397, -0.35318544,  0.86060953, -0.62072904, -1.88437345,
       -0.73084331, -0.38931328, -0.34893842, -0.42514096,  0.50346126,
       -1.83135396,  1.86151471, -0.62863496, -1.24084729,  0.48486199,
        0.2096301 , -1.26222657,  0.37176573,  0.70150296, -1.56197753,
        1.26871009, -2.50964819, -0.43427879, -0.41328323,  0.09

In [14]:
# 평균 0이고, 표준편차가 1인 정규분포를 따르는 임의의 실수 100개
rand3 = np.random.normal(0, 1, 100)
rand3

array([-0.24832219,  0.7337451 , -0.08895051, -0.19082324, -0.17356262,
       -0.15139216, -1.04911066, -0.68895594, -0.04540994,  0.26300477,
        0.10902452,  1.61040545, -0.69256942, -0.80833171, -0.83429385,
        0.11625249,  0.97749457,  0.0453549 , -0.12467663, -1.7708909 ,
       -0.00233156,  0.01630127, -1.37646436,  1.19083387, -0.17882996,
       -1.03378329,  0.36681942,  0.83903946,  0.91211352,  0.26438753,
       -2.02420141, -0.14660057,  0.05524003,  1.23952807, -0.53423934,
        0.46694781,  1.58448394,  0.16602709,  2.19135508, -0.72733528,
       -0.53019525,  0.24901584, -0.2781015 , -0.4648397 ,  0.41507188,
       -0.50888301, -0.19991473, -1.23382221, -0.25101829, -1.37396135,
        0.21759171,  0.83478121, -0.35957485, -0.88044715, -1.00480919,
        1.40305303,  0.12683224,  2.21696571,  0.87873025, -0.20688827,
        0.29646308, -0.24743556, -0.80695309,  1.04116513, -1.13594428,
        0.04327668, -0.36552667, -1.55548345,  0.62182564,  0.53